### ISSUE TITLE
Web demo

### ISSUE THREAD

**Issue by terrakok** [gabrieldrn/carbon-compose#11]
Since there is web app you can upload it to the github pages to showcase the catalog app.
You could take a look at github action configs here: https://github.com/terrakok/compose-material-3-gallery

**Comment by gabrieldrn** [comment]
Love the idea! But I've planned to use the github pages of the repo as the documentation website, can the two coexist?

**Comment by gabrieldrn** [comment]
I did some tests while writing the docs and I was able to have mkdocs + dokka + catalog app locally so It may work with GH pages. Sorry if I sound dumb, this is pretty new to me while having only little knowledge in web development. 😅

**Comment by gabrieldrn** [comment]
Catalog app is now published alongside documentation website and Dokka!
-> https://gabrieldrn.github.io/carbon-compose
-> https://gabrieldrn.github.io/carbon-compose/catalog/index.html
